<div>
    <div class="d-flex flex-wrap align-items-center justify-content-between gap-2 mb-4 pb-3 border-bottom">
        <h1 class="h4 mb-0">{{ __('All Reports') }}</h1>
    </div>

    <div class="card shadow-sm mb-3">
        <div class="card-body">
            <div class="row g-3">
                <div class="col-md-6">
                    <input type="text" class="form-control" wire:model.live.debounce.300ms="search" placeholder="{{ __('Search by project name...') }}">
                </div>
            </div>
        </div>
    </div>

    <div class="card shadow-sm">
        <div class="table-responsive">
            <table class="table table-hover mb-0 align-middle">
                <thead class="table-light">
                    <tr>
                        <th>{{ __('Project') }}</th>
                        <th>{{ __('Generated By') }}</th>
                        <th>{{ __('Generated At') }}</th>
                        <th>{{ __('Tasks') }}</th>
                        <th>{{ __('Completed') }}</th>
                        <th>{{ __('Delayed') }}</th>
                        <th>{{ __('Actions') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($reports as $report)
                        <tr>
                            <td>
                                <a href="{{ route('projects.show', $report->project) }}" class="text-decoration-none fw-semibold">
                                    {{ $report->project->name }}
                                </a>
                            </td>
                            <td>{{ $report->creator->name }}</td>
                            <td>{{ $report->generated_at->format('M j, Y H:i') }}</td>
                            <td>{{ $report->summary_data['total_tasks'] }}</td>
                            <td>{{ $report->summary_data['completed_tasks'] }}</td>
                            <td>
                                @if ($report->summary_data['delayed_tasks'] > 0)
                                    <span class="badge bg-danger">{{ $report->summary_data['delayed_tasks'] }}</span>
                                @else
                                    <span class="badge bg-success">0</span>
                                @endif
                            </td>
                            <td>
                                <a href="{{ route('projects.show', $report->project) }}" class="btn btn-sm btn-outline-primary">
                                    {{ __('View Report') }}
                                </a>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="7" class="text-center text-muted py-4">
                                {{ __('No reports found.') }}
                            </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        @if ($reports->hasPages())
            <div class="card-footer">
                {{ $reports->links() }}
            </div>
        @endif
    </div>
</div>
