<div>
    <div class="card shadow-sm">
        <div class="card-header py-2 fw-semibold d-flex align-items-center justify-content-between">
            <span>{{ __('Recent Reports') }}</span>
            <a href="{{ route('reports.index') }}" class="btn btn-sm btn-outline-primary">{{ __('View All') }}</a>
        </div>
        <div class="card-body">
            @if ($reports->isEmpty())
                <p class="text-muted mb-0">{{ __('No reports generated yet.') }}</p>
            @else
                <div class="list-group list-group-flush">
                    @foreach ($reports as $report)
                        <div class="list-group-item px-0">
                            <div class="d-flex justify-content-between align-items-start">
                                <div>
                                    <h6 class="mb-1">
                                        <a href="{{ route('projects.show', $report->project) }}" class="text-decoration-none">
                                            {{ $report->project->name }}
                                        </a>
                                    </h6>
                                    <p class="mb-1 small text-muted">
                                        {{ __('Generated by') }} {{ $report->creator->name }} {{ __('on') }} {{ $report->generated_at->format('M j, Y') }}
                                    </p>
                                    <div class="small">
                                        <span class="badge bg-primary">{{ $report->summary_data['total_tasks'] }} {{ __('tasks') }}</span>
                                        <span class="badge bg-success">{{ $report->summary_data['completed_tasks'] }} {{ __('completed') }}</span>
                                        @if ($report->summary_data['delayed_tasks'] > 0)
                                            <span class="badge bg-danger">{{ $report->summary_data['delayed_tasks'] }} {{ __('delayed') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <a href="{{ route('projects.show', $report->project) }}" class="btn btn-sm btn-outline-secondary">
                                    {{ __('View Report') }}
                                </a>
                            </div>
                        </div>
                    @endforeach
                </div>
            @endif
        </div>
    </div>
</div>
